# ---------- 顶层 ----------
seed: 3407
active_datasets: [CSL_Daily]

# 顶层 temporal 仅作兜底（可留空或删掉）
temporal: {}

# ---------- 数据集配置 ----------
datasets:
  CSL_Daily:
    root: /home/pxl416/PeixiLiu/px_proj/px_data/csl-daily-frames-512x512/
    rgb_dir: sentence                         # 相对 root
    split_file: sentence_label/split_1.txt    # 相对 root
    max_text_len: 128
    use_rgb:  true
    use_pose: false
    use_text: true
    token_level: char

    # ✅ 这个块是“CSL_Daily 专用”的 temporal / 增强
    temporal:
      ratio: 0.25
      jitter: true
      min_frames: 4         # mini 数据若太短先设 1 验证路径，再调回 4/8
      max_frames: 32
      augment:
        size: 224
        channel: rgb
        degrees: 5.0
        translate: 0.05
        scale: [0.9, 1.1]
        shear: 2.0
        hue: 0.015
        saturation: 0.40
        brightness: 0.40
        contrast: 0.20
      augment_val:
        enable: false
        size: 224
        channel: rgb
        gray_as_rgb: false
        mean: [0.485, 0.456, 0.406]
        std:  [0.229, 0.224, 0.225]

  CSL_News:
    rgb_dir:  data/mini_CSL_News/rgb
    pose_dir: data/mini_CSL_News/pose
    train_labels: data/mini_CSL_News/train_label.json
    val_labels:   data/mini_CSL_News/val_label.json
    test_labels:  data/mini_CSL_News/test_label.json
    use_rgb:  true
    use_pose: true
    use_text: true
    token_level: char

    # ✅ News 专用 temporal（示例）
    temporal:
      T: 32
      jitter: true
      random_offset: true
      augment_train:
        enable: true
        size: 224
        channel: rgb
        gray_as_rgb: false
        degrees: 5.0
        translate: 0.05
        scale: [0.9, 1.1]
        shear: 2.0
        enable_flip: false
        hue: 0.015
        saturation: 0.40
        brightness: 0.40
        contrast: 0.20
        cutout_p: 0.10
        cutout_max_area: 0.04
        cutout_num: [1, 2]
        mean: [0.485, 0.456, 0.406]
        std:  [0.229, 0.224, 0.225]
      augment_val:
        enable: false
        size: 224
        channel: rgb
        gray_as_rgb: false
        mean: [0.485, 0.456, 0.406]
        std:  [0.229, 0.224, 0.225]

# ---------- 其余（保持不变即可，注意避免重复键） ----------
mode: "pretrain"

Encoders:
  pose: { name: "PoseEncoder", output_dim: 512 }
  rgb:  { name: "RGBEncoder",  output_dim: 512 }
  text: { name: "TextEncoder", model_path: "sentence-transformers/all-MiniLM-L6-v2", output_dim: 384 }

Pretraining:
  task: "contrastive"
  loss: "infoNCE"
  temperature: 0.07
  projection_dim: 256

Evaluation:
  retrieval:   { enabled: true, head: "RetrievalHead", rgb_in: 512, text_in: 384, proj_dim: 256, temperature: 0.07 }
  recognition: { enabled: true, head: "RecognitionHeadCTC", in_dim: 512, num_classes: 2000, hidden_dim: 512, num_layers: 2, dropout: 0.1, blank_id: 0 }
  translation: { enabled: true, head: "TranslationHeadMT5", in_dim: 512, vocab_size: 30000, mt5_path: google/mt5-base, hidden_dim: 768, label_smoothing: 0.1, lang: Chinese, max_length: 128 }

Fusion:
  pose_rgb:  { enabled: false }
  pose_text: { enabled: false }
  rgb_text:  { enabled: false }

Training:
  epochs: 10
  batch_size: 8
  learning_rate: 1e-4
  grad_clip: 1.0

optimizer:
  type: "adam"
  scheduler: "cosine"

wandb:
  use: True
#  api_key: 0c563568ac7ebb0941d93b54803b7101d16280b6
  run_name: daily_all_1018
  project: Uni-slm

save_dir: checkpoints/daily_all_1018
